export const GET_SHIPPING_ADDRESS = "GET_SHIPPING_ADDRESS";
export const GET_BILLING_ADDRESS = "GET_BILLING_ADDRESS";
export const CHANGE_USER_INPUT_DATA = "CHANGE_USER_INPUT_DATA";
export const UPDATED_USER_DATA = "UPDATED_USER_DATA";
export const GET_USER_UPDATED_DATA = "GET_USER_UPDATED_DATA";