export const GET_SHIPPING_ADDRESS = "GET_SHIPPING_ADDRESS";
export const GET_BILLING_ADDRESS = "GET_BILLING_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const LOADING_ADDRESS = "LOADING_ADDRESS";