export const INIT_FEATURED_PRODUCT_LIST = "INIT_FEATURED_PRODUCT_LIST";
export const GET_FEATURED_PRODUCT_LIST = "GET_FEATURED_PRODUCT_LIST";
export const FETCH_FEATURED_PRODUCT_LIST_FAILED = "FETCHED_FEATURED_PRODUCT_LIST_FAILED";