export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SHOP_BY_CATEGORIES_LIST = "GET_SHOP_BY_CATEGORIES_LIST";
export const FETCH_SHOP_BY_CATEGORIES_LIST_FAILED = "FETCH_SHOP_BY_CATEGORIES_LIST_FAILED";
