export const INIT_SHOP_BY_CATEGORIES_LIST = "INIT_SHOP_BY_CATEGORIES_LIST";
export const GET_SHOP_BY_CATEGORIES_LIST = "GET_SHOP_BY_CATEGORIES_LIST";
export const FETCH_SHOP_BY_CATEGORIES_LIST_FAILED =
  "FETCH_SHOP_BY_CATEGORIES_LIST_FAILED";
