export const INIT_FASTEST_DELIVERY_PRODUCT = "INIT_FASTEST_DELIVERY_PRODUCT";
export const GET_FASTEST_DELIVERY_PRODUCT = "GET_FASTEST_DELIVERY_PRODUCT";
export const FETCH_FASTEST_DELIVERY_PRODUCT_FAILED = "FETCH_FASTEST_DELIVERY_PRODUCT_FAILED";