export const INIT_FASTEST_DELIVERY_PRODUCT = "INIT_FASTEST_DELIVERY_PRODUCT";
export const GET_FASTEST_DELIVERY_PRODUCT = "GET_FASTEST_DELIVERY_PRODUCT";

export const GET_FASTEST_DELIVERY_PRODUCT_DETAILS =
  "GET_FASTEST_DELIVERY_PRODUCT_DETAILS";
export const RESET_FASTEST_DELIVERY_PRODUCT_DETAILS =
  "RESET_FASTEST_DELIVERY_PRODUCT_DETAILS";

export const ERROR_OCCURRED = "ERROR_OCCURRED";
