export const GET_CATEGORY_WISE_PRODUCT_LIST = "GET_CATEGORY_WISE_PRODUCT_LIST";

export const INIT_PRODUCT_LIST = "INIT_PRODUCT_LIST";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
